#Github Workflow to find and notify about misspellings
#
#SPDX-FileCopyrightText: 2025 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Codespell spelling check"

on:
  push:
  pull_request:

jobs:
  codespell:
    name: Find and notify about common misspellings
    runs-on: ubuntu-latest
    # This should not fail the whole workflow run
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install codespell
      run: pip install "codespell==2"
    - name: Run codespell
      run: codespell
